"""
Service layer for interacting with the Anthropic Claude API via OpenRouter.

OpenRouter provides a unified gateway to many LLMs (Claude, GPT-4, Mistral, etc.)
via the standard Anthropic SDK interface, simply using a different base_url and API key.

How it works:
1. Client makes an HTTP POST request to `/chat/` with JSON body {"message": "..."}.
2. FastAPI Router receives the request and routes it to the LLM service layer.
3. This service calls OpenRouter's API endpoint using the Anthropic SDK client.
4. The response text is extracted and returned to the router.

Environment Variables required:
- ANTHROPIC_API_KEY: Your OpenRouter API key (starts with sk-or-...)
- OPENROUTER_MODEL: The model slug, e.g. "anthropic/claude-opus-4-5"
                   or "anthropic/claude-3-5-sonnet"
"""

import logging
from anthropic import Anthropic, APIError

from app.core.config import settings

logger = logging.getLogger(__name__)

# OpenRouter API base URL
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"

# Global variable for lazy client caching
_client = None


def _get_client() -> Anthropic:
    """
    Lazily initialize the Anthropic SDK client pointed at OpenRouter.
    Prevents crashes at startup if the API key is not yet configured.
    """
    global _client
    if _client is not None:
        return _client

    # Prefer OPENROUTER_API_KEY, fall back to ANTHROPIC_API_KEY
    api_key = settings.openrouter_api_key or settings.anthropic_api_key
    if not api_key:
        raise ValueError(
            "No API key found. Please set OPENROUTER_API_KEY in your .env file."
        )

    _client = Anthropic(
        api_key=api_key,
        base_url=OPENROUTER_BASE_URL,
    )
    return _client


def generate_response(
    message: str,
    system_prompt: str = "You are a helpful AI assistant.",
) -> str:
    """
    Calls the Claude model via OpenRouter using the Anthropic SDK.

    Args:
        message (str): The user message prompt.
        system_prompt (str): System-level instructions for the model.

    Returns:
        str: The response text generated by the model.

    Raises:
        ValueError: If the message is empty or API key is missing.
        RuntimeError: If the API returns an error.
    """
    # 1. Input validation
    if not message or not message.strip():
        raise ValueError("Message input cannot be empty.")

    # 2. Get lazily initialized client
    client = _get_client()

    # 3. Resolve model name from settings (default: claude-opus-4-5 on OpenRouter)
    model = settings.openrouter_model or "anthropic/claude-opus-4-5"
    logger.info(f"Calling OpenRouter with model: {model}")

    try:
        # 4. Call via standard Anthropic SDK messages.create()
        response = client.messages.create(
            model=model,
            max_tokens=4096,
            system=system_prompt,
            messages=[
                {
                    "role": "user",
                    "content": message,
                }
            ],
        )

        # 5. Extract clean text from response
        if not response.content:
            raise ValueError("Empty content returned from OpenRouter API.")

        return response.content[0].text

    except APIError as e:
        raise RuntimeError(f"Anthropic Claude API error: {str(e)}")
    except Exception as e:
        raise RuntimeError(f"Unexpected error during Claude response generation: {str(e)}")


import httpx
import json

def generate_response_stream(
    message: str,
    system_prompt: str = "You are a helpful AI assistant.",
):
    """
    Stream a response from the Claude model via OpenRouter token-by-token.
    Uses standard Server-Sent Events (SSE) chat/completions endpoint for compatibility.
    """
    if not message or not message.strip():
        raise ValueError("Message input cannot be empty.")

    api_key = settings.openrouter_api_key or settings.anthropic_api_key
    if not api_key:
        yield "\n[Error: No API key found. Please set OPENROUTER_API_KEY in .env]"
        return

    model = settings.openrouter_model or "anthropic/claude-opus-4-5"
    logger.info(f"Calling OpenRouter SSE stream with model: {model}")

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }

    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": message},
        ],
        "stream": True,
    }

    try:
        with httpx.stream(
            "POST",
            "https://openrouter.ai/api/v1/chat/completions",
            headers=headers,
            json=payload,
            timeout=60.0,
        ) as response:
            if response.status_code != 200:
                try:
                    err_json = response.json()
                    err_msg = err_json.get("error", {}).get("message", "Unknown error")
                except Exception:
                    err_msg = f"HTTP {response.status_code}"
                yield f"\n[OpenRouter Stream Error: {err_msg}]"
                return

            for line in response.iter_lines():
                if not line or not line.strip():
                    continue
                if line.startswith("data: "):
                    data_str = line[6:].strip()
                    if data_str == "[DONE]":
                        break
                    try:
                        data_json = json.loads(data_str)
                        choices = data_json.get("choices", [])
                        if choices:
                            content = choices[0].get("delta", {}).get("content", "")
                            if content:
                                yield content
                    except Exception:
                        continue
    except Exception as e:
        logger.error(f"OpenRouter streaming connection error: {e}")
        yield f"\n[Connection Error: {str(e)}]"